project:
  type: website
  output-dir: _site
  render:
    - index.qmd
  resources:
    - assets/**
    - classlib/classlib/quarto/**

metadata-files:
  - classlib/classlib/quarto/website/hickernell-website.yml
  - classlib/classlib/quarto/metadata/hickernell-texts.yml

website:
  title: "Sampling More Strategically"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/StrategicSampling.html
        text: Talk slides
    right:
      - text: Repository
        icon: github
        href: https://github.com/fjhickernell/StrategicSamplingColloquium
  page-footer:
    left: "© 2026 Fred J. Hickernell · Illinois Institute of Technology"

format:
  html:
    css:
      - classlib/classlib/quarto/website/hickernell-website.css
    include-in-header:
      - classlib/classlib/quarto/slides/hickernell-latex-macros.js
    link-external-newwindow: true

execute:
  warning: false
  message: false
